swagger: '2.0'
info:
  description: 'Petstore app, work in progress by the team!'
  version: 1.0.0-SNAPSHOT
  title: Swagger Petstore
host: localhost
basePath: /api/
tags:
  - name: pet
    description: Everything about your Pets
schemes:
  - http
paths:
  /pets:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      operationId: addPet
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '201':
          description: Created
    get:
      tags:
        - pet
      summary: Get all pets from the store
      operationId: getPets
      produces:
        - application/json
      responses:
        '200':
          description: Operation completed
  '/pet/{petId}':
    get:
      tags:
        - pet
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Operation completed
          schema:
            $ref: '#/definitions/Pet'
        '404':
          description: Pet not found
    post:
      tags:
        - pet
      summary: Updates a pet in the store with form data
      operationId: updatePetWithForm
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          description: ID of pet that needs to be updated
          required: true
          type: integer
          format: int64
        - name: name
          in: formData
          description: Updated name of the pet
          required: false
          type: string
        - name: status
          in: formData
          description: Updated status of the pet
          required: false
          type: string
      responses:
        '200':
          description: Operation completed
    delete:
      tags:
        - pet
      summary: Deletes a pet
      description: ''
      operationId: deletePet
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          description: Pet id to delete
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Pet deleted
        '404':
          description: Pet not found
definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
        example: Droopy
      status:
        type: string
        example: sold
